### PR TITLE
Fixes data type casts inside CTE of ctasHack

### PR DESCRIPTION
**Pull request by pavgra**
fixes https://github.com/OHDSI/DatabaseConnector/issues/102#issuecomment-532719850

### CODE REVIEW

**Comment by schuemie** [comment]
I don't think this is necessary (as discussed in the issue. Use the develop version of SqlRender for now to avoid the problem

**Comment by pavgra** [comment]
But this problem appeared exactly on the `develop` version of DatabaseConnector and the PR targets the `develop`. How would the develop version of SqlRender help if the Redshift's source SQL lacks CASTs?

**Comment by schuemie** [comment]
The problem isn't the lacking CASTs (the first row has the casts). The problem is the cast to TEXT that is erroneously added to the second row.

If you get the SqlRender develop version, it will work (I've tested this).

**Comment by pavgra** [comment]
Ah, now I see:
`SELECT CAST('9' AS INTEGER)` in the first line and `SELECT CAST('9' as TEXT)` in the second - missed that and paid attention to the second value which is string `'260139'` versus integer in the first line. Ok, will try the latest SqlRender, thank you.

**Pull request closed without merging**
