### PR TITLE
Update BigQuery driver.

### PR DESCRIPTION
**Pull request by lastomato**

### CODE REVIEW

**Comment by schuemie** [comment]
I'm sorry, I don't feel comfortable accepting a closed-source binary without a clear trace of its origin. @myounglai : you uploaded the original version of this driver. Can you vouch for this new version's integrity?

**Comment by lastomato** [comment]
The code is open sourced here: https://github.com/myounglai/starschema-bigquery-jdbc/tree/dml/, this binary was built from HEAD of this branch.

**Comment by myounglai** [comment]
Yes, confirmed.  Jie is taking over this work from me and is building updates from the same branch that I used for the previous versions.

**Comment by schuemie** [comment]
Ok, great! Sorry, just being careful. Will merge now

**Comment by t-abdul-basser** [comment]
Thanks @myounglai!

Welcome @lastomato!
 
Thanks @schuemie for being careful!

**Pull request merged**
