### PR TITLE
Ability to apply callback function to process batched data written to andromeda objects

### LINKED ISSUE #158: Error when using dbFetch (possibly due to integer64 support)
When attempting to use dbFetch the following error occurs:

```
DatabaseConnector::dbFetch(res = queryResult)
Error in rJava::.jcall(res@content, "[Ljava/lang/String;", "getString",  : 
  java.lang.ClassCastException: class [I cannot be cast to class [Ljava.lang.String; ([I and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
```

Steps to reproduce (confirmed on postgres and redshift):
```
connection <- connect(connectionDetails)
queryResult <- dbSendQuery(connection, "SELECT * FROM cdm.person LIMIT 10")
data <- dbFetch(queryResult)
```

This appears to be caused by the call [here](https://github.com/OHDSI/DatabaseConnector/blob/8a34f01d92a11832cb2bdb07e44385f33e428802/R/DBI.R#L272)

Which does not process the correct column types as is done in [lowLevelQuery](https://github.com/OHDSI/DatabaseConnector/blob/8a34f01d92a11832cb2bdb07e44385f33e428802/R/Sql.R#L128)

I have a patch incoming shortly.

### LINKED ISSUE #159: Ability to apply callback function to process batched data written to andromeda objects
Currently, modifying large data being pulled out of the database requires writing the data to an andromeda object, then reading the data an performing the process. The IO time of this rea -> write -> read -> process -> write is prohibitively slow for many applications.

I am suggesting the ability to apply a non-sql function to the returned batches of data before they are written to the andromeda object.

A use case example is the following:

```

 modifyBatchedData <- function(.data) {
    .data$log_rr <- computeRateRatios(.data)
    .data$p <- EmpiricalCalibration::computeTraditionalP(.data$log_rr, .data$log_se_rr)
    return(.data)
  }

sql <- "SELECT * FROM my_scc_results;"
renderTranslateQuerySqlToAndromeda(connection, sql, andromeda = andromeda, andromedaTableName = "my_scc_results", modifyBatchedData = modifyBatchedData)
```

Naturally, It would only be possible to compute this function for row wise results that don't require the entire data set as the callback above would only have access to each batch (which is of an unknown size).

I have tried a similar approach in a [branch of SelfControlledCohort](https://github.com/OHDSI/SelfControlledCohort/blob/e0aa77e001ec2ae29dfce84081df46c0d65f48cb/R/SelfControlledCohort.R#L128) (albeit writing CSV files by batch) and the speed up is considerable. I can see applications for doing this with andromeda objects.

### PR DESCRIPTION
**Pull request by azimov**
Fixes #158

Resolves #159 

Changes in this PR:

* Modified all uses of column fetching from JDBC queries to use the same function
* Tidy up of column wise data processing to use only a single loop (rather than multiple modifications of the same data)
* Added callback function to renderTranslateQuerySqlToAndromeda that allows batch by batch alterations to a dataframe before it is written to the andromeda table
* Added test cases for new modifyBatchedData callback
* Fixed broken db fetch call (issue with 64 bit strings)
* Added test cases for using dbFetch calls

### CODE REVIEW

**Comment by schuemie** [comment]
Could you help me understand why you've opted for a callback function in the Andromeda function? This is seems a horribly specific solution. I would think that if dbFetch worked properly, you wouldn't need the callback function? You could just get your data in batches, and then decide what to do with it, like write those batches to a single Andromeda, or write each batch to its own RDS file (which I think we discussed for SCC).

**Comment by azimov** [comment]
> Could you help me understand why you've opted for a callback function in the Andromeda function? This is seems a horribly specific solution.

The use of dbFetch can now be used, but this was an attempt at providing a general solution to this problem that may occur for other users. My thought is that a common occurrence when reading large data sets to an andromeda file will be to modify them with some  R code as they are written to the disk. The  approach to do this currently is  `read from db` -> `write to andromeda` -> `read from andromeda` -> `process` -> `write to andromeda`. This patch allows a faster pipeline, `read from db` -> `process` -> `write to andromeda`.  Currently, the only way for a package user to do is to replicate code from `lowLevelQuerySqlToAndromeda`.

I also implemented it in the andromeda calls because I noted that they don't use the ```DatabaseConnectorResult``` class from DBI.R, which is used by `dbSendQuery` and `dbFetch`. However, on closer inspection I think that the implementations could probably be unified further given the fix to dbFetch.

**Comment by schuemie** [comment]
But if `dbFetch` works as it is supposed to they don't need to replicate the code in `lowLevelQuerySqlToAndromeda`, right? Just a call to `dbSendQuery` and then `dbFetch`.

Sorry for pushing back, but I'm always very wary of code that serves one very specific use case only. Imagine someone want to do what your proposing (process right after fetching), but doesn't want to write to Andromeda. Do we add a new argument that say's 'dontWriteToAndromeda'? Before you know it we have a million arguments for every specific use case, and nobody will understand it anymore (and we need a million unit tests to make sure they all work) Better to have a single solution that in general supports the flow: 

- Do query
- Get data in batches
- Allow user to process each batch, and do with it what they want (e.g. write to a single Andromeda)
 
If `dbSendQuery` and `dbFetch` can't support that, we need to fix that.

**Comment by schuemie** [comment]
Thanks @azimov ! I like the direction you're going with `renderTranslateQueryApplyBatched`. I do have 1 suggestion: could we add an argument to the callback function called `position` that indicates the row number of the batch in the overall set? This would be similar to how `readr read_csv_chunked()` works (although I think they're changing that to something awful in newer versions). So `position` would be equal to 1 in the first batch, and if the batch is 1000 rows, `position` would be 1001 for the next batch. That way we don't need the global `first` variable in your example:

```r
 writeBatchesToAndromeda <- function(data, position) {
    data$p <- EmpiricalCalibration::computeTraditionalP(data$logRr, data$logSeRr)
    if (position == 1) {
        bigResults$rrs <- data
    } else {
        Andromeda::appendToTable(bigResults$rrs, data)
    }
}
```

I would also add a `...` argument so users can specify additional parameters to pass to the callback function. See [here](https://github.com/OHDSI/Andromeda/blob/master/R/Operations.R#L21) for an example.

**Comment by azimov** [comment]
Great idea @schuemie! I have updated the branch. One note is that the use of ellipsis isn't possible because this is used by the Sql render call. I have used a separate args list instead.

**Review by schuemie — APPROVED** [review]

**Pull request merged**
