### PR TITLE
issues-113 write executeBigQueryBatch using multivalues-insert

### LINKED ISSUE #113: insertTable fails on BigQuery
The insertTable function fails on BigQuery when trying to insert a dataframe as a table.  Throws a JDBC driver error that batched and streamed parameters are not supported.   
```
DatabaseConnector::insertTable(connection = connection, tableName = "results.testTable", data=df, createTable = TRUE, tempTable = FALSE)
java.sql.SQLException: [Simba][BigQueryJDBCDriver](100036) Batched and streamed parameters not supported.
	at com.simba.googlebigquery.googlebigquery.dataengine.BQAbstractExecutor.clearPushedParamData(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.doClearBatch(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.clearBatch(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executePreparedAnyBatch(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.SPreparedStatement.executeBatch(Unknown Source)
Caused by: com.simba.googlebigquery.support.exceptions.GeneralException: [Simba][BigQueryJDBCDriver](100036) Batched and streamed parameters not supported.
	... 5 more
```

The OHDSI/DataQualityDashboard uses this to try to insert the results as a table : https://github.com/OHDSI/DataQualityDashboard/issues/98#issuecomment-595951134

### PR DESCRIPTION
**Pull request by YaroslavTir**
Fixes #113

### CODE REVIEW

**Comment by schuemie** [comment]
Thanks! @YaroslavTir , I just [made some minor changes to your code, and rebuilt the jar file](https://github.com/OHDSI/DatabaseConnector/commit/ff0ebdf238b299c96268eb7297ad9b5c1d516b60) (people tend to have old JREs). Could you check if the code still works for you?

**Comment by YaroslavTir** [comment]
@schuemie thank you, next time I will keep in mind NEWS.md 
> Could you check if the code still works for you?

This works for me. I also retested big-query batch with the latest changes, it is a-ok.
> and rebuilt the jar file (people tend to have old JREs)

I fully support that, version 6 is not even supported anymore. I don't use eclipse, so If you ask me,  I would rather add some software management tools (like maven, gradle etc), but this really depends on the development process. if everybody stick with eclipse, maven can be just unnecessarily complication. 

tbh I would go one step further reducing code duplication, extract getValue part, something like this:
```
// executeBatch
        for (int i = 0; i <= rowCount; i++) {
            for (int j = 0; j < columnCount; j++) {
                statement.setObject(j + 1, getValue(i, j));
            }
            statement.addBatch();
        }
//executeBigQueryBatch
    for (int i = 0; i < size; i++) {
        for (int j = 0; j < columnCount; j++) {
            int statementIndex = columnCount * i + j + 1;
            int rowIndex  = offset + i;
            statement.setObject(statementIdex, getValue(rowIndex, j));
        }
    }

...

```
    private Object getValue(int rowIndex, int columnIndex) {

        if (columnTypes[columnIndex] == INTEGER) {
            int value = ((int[]) columns[columnIndex])[rowIndex];
            if (value == Integer.MIN_VALUE) return null;
            return value;
        } else if (columnTypes[columnIndex] == NUMERIC) {
            double value = ((double[]) columns[columnIndex])[rowIndex];
            if (Double.isNaN(value)) return null;
            return value;
        } else if (columnTypes[columnIndex] == DATE) {
            String value = ((String[]) columns[columnIndex])[rowIndex];
            return java.sql.Date.valueOf(value);
        } else if (columnTypes[columnIndex] == DATETIME) {
            String value = ((String[]) columns[columnIndex])[rowIndex];
            return java.sql.Timestamp.valueOf(value);
        } else if (columnTypes[columnIndex] == BIGINT) {
            long value = ((long[]) columns[columnIndex])[rowIndex];
            if (value == Long.MIN_VALUE) return null;
            return value;
        } else {
            String value = ((String[]) columns[columnIndex])[rowIndex];
            return value;
        }
    }
```

**Comment by schuemie** [comment]
I took your idea, but I don't trust the various JDBC implementation to play nice with setObject. Instead I [did this](https://github.com/OHDSI/DatabaseConnector/commit/1dbfb3f780f107f3323a44e8b378e62d7c9ac84a#diff-770b6f97a63154cb7ba2c920ff0516baR60). Could you test this on BigQuery?

Maven is fine too. Would you mind creating a POM file?

**Comment by YaroslavTir** [comment]
@schuemie I will test it tomorrow and add maven later this week(as soon as finalize another story) I am thinking about adding JUnit tests for java part. What do you think about this?

**Comment by schuemie** [comment]
I'd prefer relying on [R's unit testing framework](https://github.com/OHDSI/DatabaseConnector/tree/master/tests/testthat), since those tests will be automatically executed in travis.

**Comment by YaroslavTir** [comment]
> I'd prefer relying on [R's unit testing framework](https://github.com/OHDSI/DatabaseConnector/tree/master/tests/testthat), since those tests will be automatically executed in travis.

Fine by me, just don't have too much experience with R. I have tested the last changes against BigQuery, looks alright.

**Pull request merged**
