### PR TITLE
dplyr integration work in progress

### PR DESCRIPTION
**Pull request by ablack3**
This PR fixes one problem with using dplyr with a DatabaseConnector connection by changing the quoteIdentifier to a doublequote for postgres.  #35

### CODE REVIEW

**Comment by schuemie** [comment]
Would it be possible to automatically set `identifierQuote` and `stringQuote` based on the DBMS?

**Comment by ablack3** [comment]
> Would it be possible to automatically set `identifierQuote` and `stringQuote` based on the DBMS?

Yes we can set it when we create the connection. I changed the default quote to ". Any dbms that don't use a double quote can be set automatically when the connection is created. The user will never need to think about the quote identifier.

I got oracle working which required using dbplyr's SQL translation. To do this I had to create a new Oracle connection class that inherits from DatabaseConnectorJdbcConnection. I think that to make this work we will need a new connection class for each dbms because dplyr's sql translation methods are dispatched based on the class of the connection which is usually specific to a single database. 

Now it looks like postgres, redshift, and oracle are working with the basic dplyr verbs.

**Comment by ablack3** [comment]
To get dplyr translation to work we need separate connection classes for each database type because the translation methods are dispatched based on the class of the connection object. This and the addition of separate driver classes for each database type better aligns with the DBI package which implements a unified database interface from R. I used these new classes to refactor the connect function into several dbConnect methods, one for each database with the goal of having all interaction with OMOP CDM databases pass through the DBI interface. This involves separating the DatabaseConnector functions into two groups: 1) functions that implement the driver/DBI backend for a particular database and 2) helper functions that call DBI generic methods and do things like load files, translate SQL. I made a video describing these changes and the rationale behind them [here](https://www.youtube.com/watch?v=Ga5jA25YhDQ).

There are still details to work out such as how can we use driver functionality defined in other R packages. Currently we use the RSQLite driver package by wrapping it inside another DBI connection object. It would be nice if OHDSI tools and the databaseConnector helper functions could work with any DBI connection object regardless of which package implements the driver.

**Comment by schuemie** [comment]
DatabaseConnector is different from DBI in that DatabaseConnector aims to support writing code that automatically runs on all the DBMS supported by DatabaseConnector (whereas code written using just DBI requires customization per DBMS). As such, I don't think we could (nor should we) make DatabaseConnector work on any DBI connection. For example, some DatabaseConnector functions use SqlRender for translation. How  would we know how to translate SQL for a previously unseen DBI connection?

**Comment by ablack3** [comment]
> DatabaseConnector is different from DBI in that DatabaseConnector aims to support writing code that automatically runs on all the DBMS supported by DatabaseConnector (whereas code written using just DBI requires customization per DBMS).

DBI is just an interface specification that describes how to talk to databases from R. DatabaseConnector implements DBI but most OHDSI queries skip this interface. The driver packages (like DatabaseConnector) implement the actual logic. DatabaseConnector differs from other driver packages in that it aims to support several databases while other drivers typically support only one. Database can support multiple databases and still use the DBI interface right? 


> As such, I don't think we could (nor should we) make DatabaseConnector work on any DBI connection. For example, some DatabaseConnector functions use SqlRender for translation. How would we know how to translate SQL for a previously unseen DBI connection?

DatabaseConnector could use the class of the connection to identify the dbms but would have to be aware of the different classes in the R driver packages. This is how dbplyr works anyway. I think it would be possible to use other drivers which is essentially the purpose of the DatabaseConnectorDbiConnection class.  This class is confusing though since all DatabaseConnectorConnections are DBIConnections. I think we can punt this for now though and focus on getting dplyr working. 

The main question I have is if the refactoring I've done is ok and we can pass all queries through the DBI methods.

image

**Comment by schuemie** [comment]
Taking a step back, these are the things I think DatabaseConnector provides:

1. A unified interface to talk to different DBMSs with the same code. A good example is handling of temp tables in the `insertTable()` function, which uses temp table emulation on those platforms that don't support temp tables. Another example is  how `executeSql()` splits SQL into separate statements, which has to be done differently for different SQL dialects.
2. A wrapper around JDBC drivers. (RSQLite was only added for testing purposes, hence it is the odd one out.)
3. Providing helper functions. Especially the ability to generate error reports when a query fails has been essential for OHDSI, where queries fail at remote sites for reasons not reproducible at a local site. Another important feature is the ability to download to Andromeda objects, although one might argue that could live in the Andromeda package.

A DatabaseConnector connection therefore provides additional functionality on top of what a DbiConnection does. I like how we now will have different connection classes extending the DatabaseConnector connection class. I don't know if it makes sense to extend that to the driver class as well.

**Pull request closed without merging**
